### ISSUE TITLE
cannot get tests to work after update

### ISSUE THREAD

**Issue by jonalexander** [learn-co-curriculum/js-basics-online-shopping-lab#21]
error message when running learn command..
setCart is defined.

  0 passing (62ms)
  1 failing

  1) shopping "before each" hook for "should add an item to the cart":
     ReferenceError: setCart is not defined
      at Context.<anonymous> (test/shopping-test.js:30:5)

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by pletcher** [comment]
@jonalexander I'm guessing you added the [`"use strict"`](https://github.com/jonalexander/js-basics-online-shopping-lab-web-0616/blame/master/shopping.js#L1) [declarations](https://github.com/jonalexander/js-basics-online-shopping-lab-web-0616/blame/master/test/shopping-test.js#L2) because of errors with `const` and/or `let`? Unfortunately, they seem to be breaking other parts of your solution. 

The best thing to do is to install an updated runtime -- simply run `npm install -g n` and then `n latest`. You might need to restart your terminal, but then you'll be good to go with _most things_ ES6 (and everything we teach in this course, at least).

You'll need to remove "strict mode", and then the tests should run.

Thanks!
